package com.example.demo700.ENums;

public enum AdvocateSpeciality {
	
	CRIMINAL_LAWYER,
	CIVIL_LAWYER,
	FAMILY_LAWYER,
	CORPORATE_LAWYER,
	CYBER_CRIME_LAWYER,
	PROPERTY_LAWYER,
	INTELLECTUAL_PROPERTY_LAWYER,
	TAX_LAWYER,
	LABOR_LAWYER,
	TRADE_LAWYER,
	BANKING_LAWYER,
	INSURANCE_LAWYER,
	WOMEN_AND_CHILD_RIGHTS_LAWYER

}
