package com.example.demo700.ENums;

public enum CasePayment {

    CASE_REQUEST_PAYMENT,
    CASE_DOCUMENT_DRAFT_PAYMENT,
    CASE_HEARING_PAYMENT,
    CASE_APPEAL_PAYMENT,
    CASE_HEARING_APPEAL_PAYMENT,
    CASE_CLOSING_PAYMENT,
    CASE_JUDGMENT_PAYMENT,
    PAPER_FINALIZE_PAYMENT,
    CASE_FILING_PAYMENT,

    // Consultation & Initial Work
    CASE_INITIAL_CONSULTATION_PAYMENT,
    CASE_LEGAL_ADVICE_PAYMENT,
    CASE_CASE_REVIEW_PAYMENT,
    CASE_CASE_EVALUATION_PAYMENT,
    CASE_CASE_STRATEGY_PAYMENT,
    CASE_CASE_PREPARATION_PAYMENT,
    CASE_EVIDENCE_COLLECTION_PAYMENT,
    CASE_DOCUMENT_REVIEW_PAYMENT,
    CASE_LEGAL_RESEARCH_PAYMENT,
    CASE_CASE_ANALYSIS_PAYMENT,

    // Documentation Work
    CASE_DOCUMENT_PREPARATION_PAYMENT,
    CASE_DOCUMENT_CORRECTION_PAYMENT,
    CASE_DOCUMENT_TRANSLATION_PAYMENT,
    CASE_DOCUMENT_NOTARIZATION_PAYMENT,
    CASE_DOCUMENT_VERIFICATION_PAYMENT,
    CASE_DOCUMENT_SUBMISSION_PAYMENT,
    CASE_DOCUMENT_RESUBMISSION_PAYMENT,
    CASE_DOCUMENT_UPDATION_PAYMENT,
    CASE_DOCUMENT_VALIDATION_PAYMENT,
    CASE_DOCUMENT_AUTHENTICATION_PAYMENT,

    // Filing & Registration
    CASE_REGISTRATION_PAYMENT,
    CASE_CASE_ACCEPTANCE_PAYMENT,
    CASE_CASE_ADMISSION_PAYMENT,
    CASE_CASE_PROCESSING_PAYMENT,
    CASE_CASE_LISTING_PAYMENT,
    CASE_CASE_SCHEDULING_PAYMENT,
    CASE_CASE_RELISTING_PAYMENT,
    CASE_CASE_REOPENING_PAYMENT,
    CASE_CASE_TRANSFER_PAYMENT,
    CASE_CASE_MERGE_PAYMENT,

    // Evidence & Investigation
    CASE_EVIDENCE_PRESENTATION_PAYMENT,
    CASE_EVIDENCE_VERIFICATION_PAYMENT,
    CASE_EVIDENCE_CHALLENGE_PAYMENT,
    CASE_EVIDENCE_ADMISSION_PAYMENT,
    CASE_EVIDENCE_REVIEW_PAYMENT,
    CASE_WITNESS_PREPARATION_PAYMENT,
    CASE_WITNESS_EXAMINATION_PAYMENT,
    CASE_WITNESS_CROSS_EXAMINATION_PAYMENT,
    CASE_EXPERT_OPINION_PAYMENT,
    CASE_INVESTIGATION_PAYMENT,

    // Court Proceedings
    CASE_PRE_HEARING_PAYMENT,
    CASE_INTERIM_HEARING_PAYMENT,
    CASE_ARGUMENT_HEARING_PAYMENT,
    CASE_FINAL_ARGUMENT_PAYMENT,
    CASE_HEARING_RESCHEDULE_PAYMENT,
    CASE_HEARING_EXTENSION_PAYMENT,
    CASE_HEARING_PREPARATION_PAYMENT,
    CASE_HEARING_ATTENDANCE_PAYMENT,
    CASE_HEARING_DOCUMENT_PAYMENT,
    CASE_HEARING_REVIEW_PAYMENT,

    // Appeals & Review
    CASE_APPEAL_PREPARATION_PAYMENT,
    CASE_APPEAL_DOCUMENT_PAYMENT,
    CASE_APPEAL_ARGUMENT_PAYMENT,
    CASE_APPEAL_REVIEW_PAYMENT,
    CASE_APPEAL_HEARING_PAYMENT,
    CASE_SECOND_APPEAL_PAYMENT,
    CASE_HIGH_COURT_APPEAL_PAYMENT,
    CASE_SUPREME_COURT_APPEAL_PAYMENT,
    CASE_REVIEW_PETITION_PAYMENT,
    CASE_REVISION_PETITION_PAYMENT,

    // Settlement & Negotiation
    CASE_MEDIATION_PAYMENT,
    CASE_ARBITRATION_PAYMENT,
    CASE_SETTLEMENT_NEGOTIATION_PAYMENT,
    CASE_OUT_OF_COURT_SETTLEMENT_PAYMENT,
    CASE_COMPROMISE_PAYMENT,
    CASE_SETTLEMENT_DOCUMENT_PAYMENT,
    CASE_SETTLEMENT_REVIEW_PAYMENT,
    CASE_SETTLEMENT_FINALIZATION_PAYMENT,
    CASE_COMPENSATION_CLAIM_PAYMENT,
    CASE_COMPENSATION_APPROVAL_PAYMENT,

    // Judgment & Post Judgment
    CASE_JUDGMENT_PREPARATION_PAYMENT,
    CASE_JUDGMENT_REVIEW_PAYMENT,
    CASE_JUDGMENT_COPY_PAYMENT,
    CASE_JUDGMENT_CERTIFICATION_PAYMENT,
    CASE_JUDGMENT_EXECUTION_PAYMENT,
    CASE_DECREE_PREPARATION_PAYMENT,
    CASE_DECREE_EXECUTION_PAYMENT,
    CASE_ORDER_COPY_PAYMENT,
    CASE_ORDER_CERTIFICATION_PAYMENT,
    CASE_ORDER_EXECUTION_PAYMENT,

    // Closing & Archival
    CASE_FINAL_SETTLEMENT_PAYMENT,
    CASE_CASE_COMPLETION_PAYMENT,
    CASE_CASE_ARCHIVE_PAYMENT,
    CASE_CASE_RECORD_PAYMENT,
    CASE_CASE_DOCUMENT_STORAGE_PAYMENT,
    CASE_CASE_HISTORY_PREPARATION_PAYMENT,
    CASE_CASE_SUMMARY_PAYMENT,
    CASE_CASE_CLOSURE_REPORT_PAYMENT,
    CASE_FINAL_LEGAL_ADVICE_PAYMENT,
    CASE_FINAL_DOCUMENT_HANDOVER_PAYMENT

}