package com.example.demo700.ENums;

public enum CasePayment {
	
	CASE_REQUEST_PAYMENT,
	CASE_DOCUMENT_DRAFT_PAYMENT,
	CASE_HEARING_PAYMENT,
	CASE_APPEAL_PAYMENT,
	CASE_HEARING_APPEAL_PAYMENT,
	CASE_CLOSING_PAYMENT,
	CASE_JUDGMENT_PAYMENT,
	PAPER_FINALIZE_PAYMENT,
	CASE_FILING_PAYMENT

}
